# -*- coding: utf-8 -*-
"""kNN_modules.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mpL1kM2SU7TiX4IuaSJJprVYhG8mGTW
"""

# kNN_modules.py
import statistics
import math

def euclidean_distance(point1, point2):
    if len(point1) != len(point2):
        raise ValueError("Input vectors must be of same length.")
    return math.sqrt(sum((a - b) ** 2 for a, b in zip(point1, point2)))

def KNN(query, known_inputs, known_outputs, k_number, show_neighbours=False):
    distances = [(euclidean_distance(query, point), idx) for idx, point in enumerate(known_inputs)]
    distances.sort()
    nearest = [known_outputs[idx] for _, idx in distances[:k_number]]
    if show_neighbours:
        print("Nearest Neighbours:", nearest)
    return statistics.mode(nearest)